# Generated by Django 5.2.3 on 2025-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='يرجى إدخال رقم الواتساب الخاص بك مع رمز الدولة (مثال: +963XXXXXXXXX)', max_length=20, null=True, verbose_name='رقم الواتساب (اختياري)'),
        ),
    ]
