# Generated by Django 5.2.3 on 2025-07-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_message_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='يتم تجميعه تلقائياً من رمز الدولة والرقم المحلي', max_length=20, null=True, verbose_name='رقم الواتساب (اختياري)'),
        ),
    ]
