"""
Django settings for DhadPlatform project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os # <<========== تم إضافة هذا الاستيراد
from pathlib import Path
from decouple import config # <<========== أضف هذا الاستيراد إذا كنت ستستخدم python-decouple

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@e&#a_y&w^p)e-i5*7+^%p1s7&8-s#)u+c&o!h0t^!y%*s)e(m' # غير هذا المفتاح في بيئة الإنتاج!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # يجب أن يكون False في بيئة الإنتاج

# هذا يسمح للوصول من مضيفين معينين (أو الجميع في وضع التطوير). في الإنتاج، ضع عنوان IP أو اسم النطاق الخاص بك
ALLOWED_HOSTS = []


# Application definition

# قائمة التطبيقات المثبتة في مشروع Django
# تتضمن تطبيقات Django المدمجة وتطبيقاتنا المخصصة
INSTALLED_APPS = [
    'django.contrib.admin', # لوحة إدارة Django
    'django.contrib.auth', # نظام المصادقة
    'django.contrib.contenttypes', # نظام الأنواع للمحتوى (مثل ربط الأذونات)
    'django.contrib.sessions', # نظام الجلسات
    'django.contrib.messages', # نظام الرسائل (لإظهار رسائل للمستخدم)
    'django.contrib.staticfiles', # لخدمة الملفات الثابتة (CSS, JS, صور)
    'django.contrib.humanize',
    
    # تطبيقاتنا المخصصة
    'core',          # تطبيقنا الأساسي، سيحتوي على نموذج المستخدم المخصص
    'registration',  # تطبيق خاص بطلبات التسجيل ونموذجها
    'academic',      # لإدارة المحتوى الأكاديمي (مواد، دروس، واجبات، اختبارات)
    'messaging',     # لنظام الرسائل والمحادثات
    'payments',      # لإدارة الاشتراكات والدفع
    'contacts',
    'dashboard',
    
]

# إعدادات البرامج الوسيطة (Middleware)
# هذه البرامج تقوم بمعالجة الطلبات والاستجابات
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # حماية أمنية
    'django.contrib.sessions.middleware.SessionMiddleware', # لإدارة جلسات المستخدمين
    'django.middleware.common.CommonMiddleware', # إعدادات عامة للطلبات/الاستجابات
    'django.middleware.csrf.CsrfViewMiddleware', # حماية ضد هجمات CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # لإدارة مصادقة المستخدمين
    'django.contrib.messages.middleware.MessageMiddleware', # لإدارة رسائل Django
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # حماية ضد Clickjacking
]

# المسار الأساسي لملفات URLs الخاصة بالمشروع
ROOT_URLCONF = 'DhadPlatform.urls'

# إعدادات القوالب (Templates)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # تحديد مجلد القوالب الرئيسي للمشروع
        'APP_DIRS': True, # السماح لتطبيقات Django بالبحث عن قوالبها في مجلدات 'templates' الخاصة بها
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# إعدادات WSGI (Web Server Gateway Interface)
# الواجهة التي يستخدمها خادم الويب (مثل Gunicorn) للتواصل مع تطبيق Django
WSGI_APPLICATION = 'DhadPlatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# إعدادات قاعدة البيانات - حالياً SQLite للاستخدام المحلي
# في بيئة الإنتاج، سنقوم بتعديلها لاستخدام Supabase (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# إعداد اللغة الرئيسية للمشروع إلى العربية
LANGUAGE_CODE = 'ar-ar'

# إعداد المنطقة الزمنية
TIME_ZONE = 'Asia/Damascus' # يمكنك تغييرها لـ 'Africa/Cairo' أو 'Asia/Riyadh' حسب بلدك

USE_I18N = True # تفعيل دعم التدويل
USE_TZ = True # تفعيل دعم المناطق الزمنية


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# المسار URL الذي ستخدم منه الملفات الثابتة (عند استخدام collectstatic)
STATIC_URL = '/static/' # <<========== يفضل إضافة الشرطة المائلة الأمامية في البداية

# مسار مجلد جمع الملفات الثابتة في الإنتاج
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # <<========== استخدم os.path.join هنا

# مجلدات إضافية حيث يبحث Django عن ملفات الـ static في وضع التطوير
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# إعدادات خاصة بمنصتنا التعليمية
# ==============================================================================

# تعريف نموذج المستخدم المخصص الخاص بنا
# هذا ضروري بعد إنشاء نموذج المستخدم في core/models.py
AUTH_USER_MODEL = 'core.User'


# ==============================================================================
# إعدادات Redirects بعد تسجيل الدخول والخروج
# ==============================================================================
LOGIN_REDIRECT_URL = '/dashboard/'   # الصفحة التي يذهب إليها المستخدم بعد تسجيل الدخول بنجاح
LOGOUT_REDIRECT_URL = '/'            # الصفحة التي يذهب إليها المستخدم بعد تسجيل الخروج (يعود للصفحة الرئيسية)
LOGIN_URL = '/login/'                # الصفحة التي يتم توجيه المستخدم إليها إذا حاول الوصول لصفحة محمية بدون تسجيل دخول
# ==============================================================================
# إعدادات ملفات الوسائط (Media Files)
# هذه الإعدادات ضرورية لتخزين الملفات المرفوعة من المستخدمين (مثل ملفات PDF، صور، فيديوهات)
# ==============================================================================
MEDIA_URL = '/media/' # المسار URL للوصول إلى ملفات الوسائط
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # <<========== استخدم os.path.join هنا


# ==============================================================================
# إعدادات خاصة بمنصة ضاد
# ==============================================================================

# ID للمادة الدراسية الخاصة باللغة العربية التي يستخدمها اختبار تحديد المستوى
# يجب عليك استبدال None بـ ID المادة الفعلية من لوحة الإدارة بعد إنشائها
ARABIC_PLACEMENT_COURSE_ID = None # مثال: 1 (إذا كان ID مادة اللغة العربية هو 1)

# عتبات الدرجات لاختبار تحديد المستوى (يمكنك تعديلها حسب الحاجة)
PLACEMENT_TEST_THRESHOLDS = {
    'beginner_max_score': 39,      # أي درجة أقل من أو تساوي 39 = مبتدئ
    'intermediate_max_score': 79,  # أي درجة بين 40 و 79 = متوسط
    # أعلى من 79 = متقدم
}