# Generated by Django 5.2.3 on 2025-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الواجب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الواجب')),
                ('due_date', models.DateTimeField(verbose_name='تاريخ التسليم النهائي')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='أقصى درجة')),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments_files/', verbose_name='ملف الواجب (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'واجب',
                'verbose_name_plural': 'الواجبات',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز الحلقة')),
                ('start_time', models.DateTimeField(verbose_name='وقت بدء الجلسة')),
                ('end_time', models.DateTimeField(verbose_name='وقت انتهاء الجلسة')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='سعة الحلقة')),
                ('required_arabic_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('any', 'أي مستوى')], default='any', help_text='المستوى المحدد في اللغة العربية المطلوب للطلاب في هذه الحلقة.', max_length=20, verbose_name='المستوى العربي المطلوب')),
            ],
            options={
                'verbose_name': 'حلقة دراسية',
                'verbose_name_plural': 'حلقات دراسية',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المادة')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'مواد دراسية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملف')),
                ('file', models.FileField(upload_to='educational_files/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'ملف تعليمي',
                'verbose_name_plural': 'الملفات التعليمية',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدرس')),
                ('youtube_link', models.URLField(help_text='الرابط الكامل لفيديو يوتيوب (غير مدرج أو خاص).', verbose_name='رابط فيديو يوتيوب')),
                ('is_recorded', models.BooleanField(default=True, verbose_name='درس مسجل')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'درس مسجل',
                'verbose_name_plural': 'الدروس المسجلة',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'بدأ المشاهدة'), ('completed', 'شوهد بالكامل')], default='started', max_length=10, verbose_name='الحالة')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'تقدم الدرس',
                'verbose_name_plural': 'تقدم الدروس',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة؟')),
            ],
            options={
                'verbose_name': 'خيار',
                'verbose_name_plural': 'الخيارات',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم البرنامج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف البرنامج')),
            ],
            options={
                'verbose_name': 'برنامج تعليمي',
                'verbose_name_plural': 'برامج تعليمية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صواب/خطأ'), ('short_answer', 'إجابة قصيرة')], default='multiple_choice', max_length=20, verbose_name='نوع السؤال')),
                ('score_points', models.PositiveIntegerField(default=1, verbose_name='نقاط السؤال')),
                ('stage', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='intermediate', help_text='مرحلة السؤال في اختبار تحديد المستوى', max_length=20, verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='student_submissions/', verbose_name='ملف التسليم')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('graded', 'تم التصحيح'), ('resubmit', 'مطلوب إعادة تسليم')], default='pending', max_length=20, verbose_name='الحالة')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='الدرجة')),
                ('teacher_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المعلم')),
            ],
            options={
                'verbose_name': 'تسليم واجب',
                'verbose_name_plural': 'تسليمات الواجبات',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة الاختبار بالدقائق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_placement_test', models.BooleanField(default=False, verbose_name='هل هو اختبار تحديد مستوى؟')),
                ('level', models.CharField(blank=True, choices=[('unassigned', 'لم يتم التحديد بعد'), ('A1', 'مستوى A1'), ('A2', 'مستوى A2'), ('B1', 'مستوى B1'), ('B2', 'مستوى B2'), ('C1', 'مستوى C1'), ('C2', 'مستوى C2'), ('native', 'متحدث أصلي')], max_length=20, null=True, verbose_name='المستوى المستهدف')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'اختبارات',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='النتيجة')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='اجتاز')),
                ('determined_level_at_this_stage', models.CharField(choices=[('unassigned', 'لم يتم التحديد بعد'), ('A1', 'مستوى A1'), ('A2', 'مستوى A2'), ('B1', 'مستوى B1'), ('B2', 'مستوى B2'), ('C1', 'مستوى C1'), ('C2', 'مستوى C2'), ('native', 'متحدث أصلي')], default='unassigned', max_length=20, verbose_name='المستوى المحدد من هذه المرحلة')),
                ('is_final_placement_result', models.BooleanField(default=False, verbose_name='هل هي نتيجة تحديد المستوى النهائية؟')),
                ('status', models.CharField(choices=[('in_progress', 'قيد التقدم'), ('completed', 'اكتملت هذه المرحلة'), ('finalized', 'تم تحديد المستوى النهائي')], default='in_progress', max_length=20, verbose_name='حالة الاختبار')),
            ],
            options={
                'verbose_name': 'نتيجة اختبار',
                'verbose_name_plural': 'نتائج الاختبارات',
                'ordering': ['-start_time'],
            },
        ),
    ]
