# Generated by Django 5.2.3 on 2025-07-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_placement_course',
            field=models.BooleanField(default=False, help_text='تُستخدم لتحديد المواد الأساسية لاختبارات تحديد المستوى.', verbose_name='هل هي مادة تحديد مستوى؟'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='answers',
            field=models.JSONField(blank=True, null=True, verbose_name='إجابات الطالب'),
        ),
        migrations.AlterField(
            model_name='class',
            name='required_arabic_level',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('any', 'أي مستوى'), ('A1', 'مستوى A1'), ('A2', 'مستوى A2'), ('B1', 'مستوى B1'), ('B2', 'مستوى B2'), ('C1', 'مستوى C1'), ('C2', 'مستوى C2'), ('native', 'متحدث أصلي')], default='any', help_text='المستوى المحدد في اللغة العربية المطلوب للطلاب في هذه الحلقة.', max_length=20, verbose_name='المستوى العربي المطلوب'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer_text', models.TextField(blank=True, null=True, verbose_name='نص الإجابة القصيرة')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هل الإجابة صحيحة؟')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجابة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='academic.question', verbose_name='السؤال')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.option', verbose_name='الخيار المختار')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers_detail', to='academic.testresult', verbose_name='نتيجة الاختبار')),
            ],
            options={
                'verbose_name': 'إجابة طالب',
                'verbose_name_plural': 'إجابات الطلاب',
                'ordering': ['question__id'],
                'unique_together': {('test_result', 'question')},
            },
        ),
    ]
