# Generated by Django 5.2.3 on 2025-07-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='المكان الحالي (المدينة/المنطقة)')),
                ('study_level', models.CharField(max_length=100, verbose_name='المستوى الدراسي')),
                ('curriculum', models.CharField(blank=True, max_length=100, null=True, verbose_name='منهاج الدراسة')),
                ('program', models.CharField(max_length=100, verbose_name='البرنامج الذي يرغب في الانضمام إليه')),
                ('grade', models.CharField(max_length=50, verbose_name='الصف/المستوى الأكاديمي')),
                ('arabic_level', models.CharField(max_length=100, verbose_name='مستوى اللغة العربية الحالي')),
                ('native_language', models.CharField(max_length=100, verbose_name='اللغة الأم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='رقم واتساب للتواصل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'تم الرفض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('preferred_payment_method', models.CharField(blank=True, choices=[('shamcash', 'شام كاش'), ('bank_transfer', 'حوالات بنكية'), ('credit_card', 'بطاقة ائتمان')], max_length=20, null=True, verbose_name='طريقة الدفع المفضلة')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request_link', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'طلب تسجيل',
                'verbose_name_plural': 'طلبات التسجيل',
            },
        ),
    ]
