# Generated by Django 5.2.3 on 2025-07-27 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': 'طلب تسجيل', 'verbose_name_plural': 'طلبات التسجيل'},
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('shamcash', 'شام كاش'), ('bank_transfer', 'حوالات بنكية'), ('credit_card', 'بطاقة ائتمان')], max_length=20, null=True, verbose_name='طريقة الدفع المفضلة'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='arabic_level',
            field=models.CharField(max_length=100, verbose_name='مستوى اللغة العربية الحالي'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المكان الحالي (المدينة/المنطقة)'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='curriculum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='منهاج الدراسة'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='grade',
            field=models.CharField(max_length=50, verbose_name='الصف/المستوى الأكاديمي'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='program',
            field=models.CharField(max_length=100, verbose_name='البرنامج الذي يرغب في الانضمام إليه'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request_link', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط'),
        ),
    ]
